[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
sort_translit = true
linemode = "none"
show_hidden = false
show_symlink = true
scrolloff = 8
mouse_events = ["click", "scroll", "touch"]
title_format = "Yazi: {cwd}"

[preview]
wrap = "yes"
tab_size = 2
max_width = 1800
max_height = 1800
image_delay = 20
image_filter = "triangle"
image_quality = 80

[input]
cursor_blink = true

[which]
sort_by = "key"
sort_sensitive = false
sort_reverse = false
sort_translit = true
